version: '3.8'
services:
  db:
    image: postgres:10.15-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db:
